language: ruby
cache: bundler
rvm:
  - "2.1.2"
node_js:
  - "0.10"
before_install:
  - cd lib/api_browser
  - npm install
  - cd ../..
script:
  - bundle exec rspec spec
  - cd lib/api_browser
  - npm test
  - cd ../..
