markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink:        pretty

# Setup
title:            Praxis
tagline:          'Rapid development for excellent APIs'
description:      'A light-weight web framework for easily building clean and consistent APIs.'
url:              http://www.praxis-framework.io
baseurl:          ''
timezone:         America/Los_Angeles
sass:
  style: :compressed

github:
  repo:           https://github.com/rightscale/praxis
navigation:
  - title:        'Intro'
    href:         '/intro'
  - title:        'Getting Started'
    href:         '/getting-started'
  - title:        'Designing APIs'
    #href:         '/design'
    subsections:
      - title:      'Media Types'
        href:       '/reference/media-types'
      - title:      'API Definition'
        href:       '/reference/api-definition'
      - title:      'Resource Definitions and Actions'
        href:       '/reference/resource-definitions'
      - title:      'Response Definitions'
        href:       '/reference/response-definitions'
      - title:      'Doc Generation'
        href:       '/reference/doc-generation'
  - title:        'Implementing APIs'
    #href:         '/app'
    subsections:
      - title:      'Application'
        href:       '/reference/application'
      - title:      'Controllers'
        href:       '/reference/controllers'
      - title:      'Requests'
        href:       '/reference/requests'
      - title:      'Responses'
        href:       '/reference/responses'
      - title:      'Handlers'
        href:       '/reference/handlers'
      - title:      'Traits'
        href:       '/reference/traits'
      - title:      'Plugins'
        href:       '/reference/plugins'
      - title:      'Extensions'
        href:       '/reference/extensions'
      - title:      'Multipart Encoding'
        href:       '/reference/multipart'
  - title:        'Praxis Internals'
    #href:         '/internals'
    subsections:
    - title:      'Bootstrapping'
      href:       '/reference/bootstrapping'
    - title:      'Request Life Cycle'
      href:       '/reference/request-life-cycle'
